<<<<<<< Updated upstream
services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
=======
version: '3.9'

services:
  chromadb:
    image: chromadb/chroma:latest
    restart: unless-stopped # Always restart unless explicitly stopped
>>>>>>> Stashed changes
    ports:
      - "8000:8000" # Host_port:Container_port
    volumes:
<<<<<<< Updated upstream
      - chroma_data:/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
    # Defining the driver is good practice, though 'local' is the default.
    driver: local
=======
      - chromadb_data:/chroma/chroma # Named volume for persistence
    environment:
      # Optional environment variables
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    healthcheck: # Basic healthcheck to ensure Chroma is ready
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  chromadb_data: # Define the named volume
>>>>>>> Stashed changes
